# This is a basic workflow to help you get started with Actions

name: Snake

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: generate github-contribution-grid-snake.svg
        uses: aelassas/snk/svg-only@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            resource/snk/github-contribution-grid-snake.svg
            resource/snk/github-contribution-grid-snake-dark.svg?palette=github-dark

      # - name: push github-contribution-grid-snake.svg to the output branch
      #   uses: crazy-max/ghaction-github-pages@v3.1.0
      #   with:
      #     target_branch: main
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}


      # - name: generate github-contribution-grid-snake.svg
      #   uses: aelassas/snk/svg-only@main
      #   with:
      #     github_user_name: ${{ github.repository_owner }}
      #     outputs: |
      #       dist/profile-snake-contrib/github-contribution-grid-snake.svg
      #       dist/profile-snake-contrib/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      # - name: push github-contribution-grid-snake.svg to the output branch
      #   uses: crazy-max/ghaction-github-pages@v3.1.0
      #   with:
      #     target_branch: main
      #     build_dir: dist
      #     keep_history: true
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
